// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbniklysqaxnzgrryjix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndibmlrbHlzcWF4bnpncnJ5aml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDU4NTMsImV4cCI6MjA3MTYyMTg1M30.fesSKespqQZR28TFCvbzAR7tfxJa50diRHlvzVL1lbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});